name: Test and Lint

on: 
  pull_request:
    branches: 
      - dev
      - main

jobs: 
  test-and-lint:
    runs-on: ubunto-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reguirements.txt
          pip install flake8 pytest
          
      - name: Run flake8 linting
        run: flake8 . #Kör linting och returnerar fel om kodstilen inte följs

      - name: Run pytest
        run: pytest #Kör alla testfiler som börjar med "test_"
        
